### ISSUE TITLE
Compilation fails: no method named `get_mut` found for struct `std::cell::UnsafeCell<T>`

### ISSUE THREAD

**Issue by Hocuri** [Septias/better-ilias#2]
Writing here instead of Discord, maybe keeps things a bit more where they belong...

When compiling (on Linux/Manjaro) I get:

<pre><font color="#55FF55"><b>➜  </b></font><font color="#55FFFF"><b>~</b></font> <font color="#5555FF"><b>git:(</b></font><font color="#FF5555"><b>master</b></font><font color="#5555FF"><b>) </b></font><font color="#FFC700"><b>✗</b></font> cd BetterIlias/Backend 
<font color="#55FF55"><b>➜  </b></font><font color="#55FFFF"><b>Backend</b></font> <font color="#5555FF"><b>git:(</b></font><font color="#FF5555"><b>master</b></font><font color="#5555FF"><b>) </b></font><font color="#FFC700"><b>✗</b></font> cargo +nightly build --release
<font color="#55FF55"><b>   Compiling</b></font> state v0.4.2 (https://github.com/SergioBenitez/state.git?rev=504ef71a#504ef71a)
<font color="#55FF55"><b>   Compiling</b></font> byteorder v1.3.4
<font color="#55FF55"><b>   Compiling</b></font> mio v0.7.7
<font color="#55FF55"><b>   Compiling</b></font> standback v0.2.17
<font color="#55FF55"><b>   Compiling</b></font> want v0.3.0
<font color="#55FF55"><b>   Compiling</b></font> aho-corasick v0.7.15
<font color="#55FF55"><b>   Compiling</b></font> stable-pattern v0.1.0
<font color="#55FF55"><b>   Compiling</b></font> tendril v0.4.1
<font color="#55FF55"><b>   Compiling</b></font> twoway v0.2.1
<font color="#55FF55"><b>   Compiling</b></font> atty v0.2.14
<font color="#55FF55"><b>   Compiling</b></font> anyhow v1.0.39
<font color="#55FF55"><b>   Compiling</b></font> atomic v0.5.0
<font color="#55FF55"><b>   Compiling</b></font> syn v1.0.64
<font color="#55FF55"><b>   Compiling</b></font> rand_core v0.5.1
<font color="#55FF55"><b>   Compiling</b></font> parking_lot v0.11.1
<font color="#55FF55"><b>   Compiling</b></font> openssl-sys v0.9.60
<font color="#55FF55"><b>   Compiling</b></font> openssl v0.10.32
<font color="#55FF55"><b>   Compiling</b></font> idna v0.2.2
<font color="#FF5555"><b>error[E0599]</b></font><b>: no method named `get_mut` found for struct `std::cell::UnsafeCell&lt;T&gt;` in the current scope</b>
  <font color="#5555FF"><b>--&gt; </b></font>/home/jonathan/.cargo/git/checkouts/state-461be979d187f8b7/504ef71/src/shim.rs:41:40
   <font color="#5555FF"><b>|</b></font>
<font color="#5555FF"><b>41</b></font> <font color="#5555FF"><b>| </b></font>            #[cfg(not(loom))] { self.0.get_mut() }
   <font color="#5555FF"><b>| </b></font>                                       <font color="#FF5555"><b>^^^^^^^</b></font> <font color="#FF5555"><b>method not found in `std::cell::UnsafeCell&lt;T&gt;`</b></font>

<font color="#FF5555"><b>error</b></font><b>: aborting due to previous error</b>

<b>For more information about this error, try `rustc --explain E0599`.</b>
<font color="#FF5555"><b>error</b></font><b>:</b> could not compile `state`.

To learn more, run the command again with --verbose.
<font color="#FFC700"><b>warning</b></font><b>:</b> build failed, waiting for other jobs to finish...
<font color="#FF5555"><b>error</b></font><b>:</b> build failed
</pre>

**Comment by Hocuri** [comment]
Oh, it was just that I didn't have the newest version of Rust installed. `rustup update` did the trick.

**Comment by Septias** [comment]
😂 Das warn schnelles Issue
